### ISSUE TITLE
Example failing with Miscellaneous Error

### ISSUE THREAD

**Issue by briviere** [sbruno81/rets-client#20] opened 2016-01-15 03:41 UTC
I tried running your METADATA-RESOURCE with debug.  I tried the same request in postman and it also returns the same message (http://rets.mresdms.com:8080/rets/rets/getMetadata?Type=METADATA-RESOURCE&Id=5280890&Format=COMPACT)

Below is the Debug output:

Debugger listening on port 16195
  rets-client:main RETS login: +0ms {}
  rets-client:request request: +18ms { debugId: 1,
  uri: 'http://rets.mresdms.com:8080/rets/rets/login',
  method: 'GET',
  headers: 
   { 'User-Agent': 'RETS node-client/3.0',
     'RETS-Version': 'RETS/1.5',
     host: 'rets.mresdms.com:8080' } }
  rets-client:request auth: +80ms { debugId: 1,
  statusCode: 401,
  headers: 
   { 'set-cookie': [ 'JSESSIONID=28CBADF39DEB6504DA69A85D3134A04A; Path=/rets' ],
     'www-authenticate': 'Digest realm="RETS Server", qop="auth", nonce="596bfb6872af39ec23e32e1885764958", opaque="ba4f0cc7fdd67d77f2590faea53e992b"',
     'content-type': 'text/html;charset=ISO-8859-1',
     'content-language': 'en-CA',
     'transfer-encoding': 'chunked',
     date: 'Fri, 15 Jan 2016 03:37:03 GMT',
     server: 'Apache Coyote/1.0',
     connection: 'close' },
  uri: 'http://rets.mresdms.com:8080/rets/rets/login' }
  rets-client:request request: +8ms { debugId: 1,
  uri: 'http://rets.mresdms.com:8080/rets/rets/login',
  method: 'GET',
  headers: 
   { 'User-Agent': 'RETS node-client/3.0',
     'RETS-Version': 'RETS/1.5',
     authorization: 'Digest username="LDON-BGRConsult", realm="RETS Server", nonce="596bfb6872af39ec23e32e1885764958", uri="/rets/rets/login", qop=auth, response="0ec8a3cdc4e2786e3da81a7102a75089", nc=00000001, cnonce="79f217921cf3442dbe79bbf085975f64", opaque="ba4f0cc7fdd67d77f2590faea53e992b"',
     referer: 'http://rets.mresdms.com:8080/rets/rets/login',
     host: 'rets.mresdms.com:8080',
     cookie: 'JSESSIONID=28CBADF39DEB6504DA69A85D3134A04A' } }
  rets-client:request response: +183ms { debugId: 1,
  headers: 
   { 'rets-version': 'RETS/1.5',
     'content-type': 'text/xml',
     'content-length': '634',
     date: 'Fri, 15 Jan 2016 03:37:03 GMT',
     server: 'Apache Coyote/1.0',
     connection: 'close' },
  statusCode: 200,
  body: '<?xml version="1.0"?>\r\n<RETS ReplyCode="0" ReplyText="Operation Successful">\r\n<RETS-RESPONSE>\r\nMemberName=IDX LEVEL LDON\r\nUser=LDON-BGRConsult\r\nMetadataVersion=1.01.001\r\nMetadataTimestamp=Sun, 27 May 2012 12:00:00 GMT\r\nMinMetadataVersion=1.01.001\r\nMinMetadataTimestamp=Sun, 27 May 2012 12:00:00 GMT\r\nTimeoutSeconds = 1800\r\nLogin=http://rets.mresdms.com:8080/rets/rets/login\r\nLogout=http://rets.mresdms.com:8080/rets/rets/logout\r\nSearch=http://rets.mresdms.com:8080/rets/rets/search\r\nGetMetadata=http://rets.mresdms.com:8080/rets/rets/getMetadata\r\nGetObject=http://rets.mresdms.com:8080/rets/rets/getObject\r\n</RETS-RESPONSE>\r\n</RETS>\r\n' }
===================================
========  System Metadata  ========
===================================
    retsVersion: RETS/1.5
    retsServer: Apache Coyote/1.0
    MemberName: IDX LEVEL LDON
    User: LDON-BGRConsult
    MetadataVersion: 1.01.001
    MetadataTimestamp: Sun, 27 May 2012 12:00:00 GMT
    MinMetadataVersion: 1.01.001
    MinMetadataTimestamp: Sun, 27 May 2012 12:00:00 GMT
    TimeoutSeconds :  1800
    Login: http://rets.mresdms.com:8080/rets/rets/login
    Logout: http://rets.mresdms.com:8080/rets/rets/logout
    Search: http://rets.mresdms.com:8080/rets/rets/search
    GetMetadata: http://rets.mresdms.com:8080/rets/rets/getMetadata
    GetObject: http://rets.mresdms.com:8080/rets/rets/getObject

  rets-client:main RETS getMetadata (streaming) +6s { Type: 'METADATA-RESOURCE', Id: '0', Format: 'COMPACT' }
  rets-client:request request: +13ms { debugId: 2,
  uri: 'http://rets.mresdms.com:8080/rets/rets/getMetadata?Type=METADATA-RESOURCE&Id=0&Format=COMPACT',
  method: 'GET',
  headers: 
   { 'User-Agent': 'RETS node-client/3.0',
     'RETS-Version': 'RETS/1.5',
     host: 'rets.mresdms.com:8080',
     cookie: 'JSESSIONID=28CBADF39DEB6504DA69A85D3134A04A' } }
  rets-client:request auth: +80ms { debugId: 2,
  statusCode: 401,
  headers: 
   { 'www-authenticate': 'Digest realm="RETS Server", qop="auth", nonce="f2ed2cee1ac06307cd172a1e1d837a9d", opaque="9ac93ef1bf2c210a85b8e70eb19de6ac"',
     'content-type': 'text/html;charset=ISO-8859-1',
     'content-language': 'en-CA',
     'transfer-encoding': 'chunked',
     date: 'Fri, 15 Jan 2016 03:37:10 GMT',
     server: 'Apache Coyote/1.0',
     connection: 'close' },
  uri: 'http://rets.mresdms.com:8080/rets/rets/getMetadata?Type=METADATA-RESOURCE&Id=0&Format=COMPACT' }
  rets-client:request request: +3ms { debugId: 2,
  uri: 'http://rets.mresdms.com:8080/rets/rets/getMetadata?Type=METADATA-RESOURCE&Id=0&Format=COMPACT',
  method: 'GET',
  headers: 
   { 'User-Agent': 'RETS node-client/3.0',
     'RETS-Version': 'RETS/1.5',
     cookie: 'JSESSIONID=28CBADF39DEB6504DA69A85D3134A04A',
     authorization: 'Digest username="LDON-BGRConsult", realm="RETS Server", nonce="f2ed2cee1ac06307cd172a1e1d837a9d", uri="/rets/rets/getMetadata?Type=METADATA-RESOURCE&Id=0&Format=COMPACT", qop=auth, response="ea3db280fb766290a96546844ad53113", nc=00000001, cnonce="7b0564d34fcc4c51afd7578f211eb205", opaque="9ac93ef1bf2c210a85b8e70eb19de6ac"',
     referer: 'http://rets.mresdms.com:8080/rets/rets/getMetadata?Type=METADATA-RESOURCE&Id=0&Format=COMPACT',
     host: 'rets.mresdms.com:8080' } }
  rets-client:request response: +251ms { debugId: 2,
  headers: 
   { 'rets-version': 'RETS/1.5',
     'content-type': 'text/xml',
     'content-length': '59',
     date: 'Fri, 15 Jan 2016 03:37:10 GMT',
     server: 'Apache Coyote/1.0',
     connection: 'close' },
  statusCode: 200 }
  rets-client:main RETS logout: +14ms {}
  rets-client:request request: +4ms { debugId: 3,
  uri: 'http://rets.mresdms.com:8080/rets/rets/logout',
  method: 'GET',
  headers: 
   { 'User-Agent': 'RETS node-client/3.0',
     'RETS-Version': 'RETS/1.5',
     host: 'rets.mresdms.com:8080',
     cookie: 'JSESSIONID=28CBADF39DEB6504DA69A85D3134A04A' } }
  rets-client:request auth: +180ms { debugId: 3,
  statusCode: 401,
  headers: 
   { 'www-authenticate': 'Digest realm="RETS Server", qop="auth", nonce="a6089c706b8ed178bd86b5e2bc7ce2bb", opaque="4f049fc9c4c84633e09ec3ed50a53f42"',
     'content-type': 'text/html;charset=ISO-8859-1',
     'content-language': 'en-CA',
     'transfer-encoding': 'chunked',
     date: 'Fri, 15 Jan 2016 03:37:10 GMT',
     server: 'Apache Coyote/1.0',
     connection: 'close' },
  uri: 'http://rets.mresdms.com:8080/rets/rets/logout' }
  rets-client:request request: +4ms { debugId: 3,
  uri: 'http://rets.mresdms.com:8080/rets/rets/logout',
  method: 'GET',
  headers: 
   { 'User-Agent': 'RETS node-client/3.0',
     'RETS-Version': 'RETS/1.5',
     cookie: 'JSESSIONID=28CBADF39DEB6504DA69A85D3134A04A',
     authorization: 'Digest username="LDON-BGRConsult", realm="RETS Server", nonce="a6089c706b8ed178bd86b5e2bc7ce2bb", uri="/rets/rets/logout", qop=auth, response="16230763c08d5b8226da252db8449e61", nc=00000001, cnonce="c21103c92ca24ba6a8e23309cdfb8b15", opaque="4f049fc9c4c84633e09ec3ed50a53f42"',
     referer: 'http://rets.mresdms.com:8080/rets/rets/logout',
     host: 'rets.mresdms.com:8080' } }
  rets-client:request response: +242ms { debugId: 3,
  headers: 
   { 'rets-version': 'RETS/1.5',
     'content-type': 'text/xml',
     'content-length': '183',
     date: 'Fri, 15 Jan 2016 03:37:10 GMT',
     server: 'Apache Coyote/1.0',
     connection: 'close' },
  statusCode: 200,
  body: '<?xml version="1.0"?>\r\n<RETS ReplyCode="0" ReplyText="Operation Successful">\r\n<RETS-RESPONSE>\r\nConnectTime = 155\r\nBilling = 1.08\r\nSignOffMessage = Goodbye\r\n</RETS-RESPONSE>\r\n</RETS>\r\n' }
ERROR: issue encountered: RetsReplyError: RETS Server replied with an error code - ReplyCode 20513 (MISC_ERROR); ReplyText: Miscellaneous Error
    at processStatus (/home/brian/rets-client/node_modules/rets-client/dist/utils/retsParsing.js:113:21)
    at null.<anonymous> (/home/brian/rets-client/node_modules/rets-client/dist/utils/retsParsing.js:126:7)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Parser.parse (/home/brian/rets-client/node_modules/rets-client/node_modules/node-expat/lib/node-expat.js:23:22)
    at Parser.write (/home/brian/rets-client/node_modules/rets-client/node_modules/node-expat/lib/node-expat.js:60:19)
    at Request.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/brian/rets-client/node_modules/rets-client/node_modules/request/request.js:959:12)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at IncomingMessage.Readable.push (_stream_readable.js:110:10)
    at HTTPParser.parserOnBody (_http_common.js:109:22)
From previous event:
    at _getMetadataImpl (/home/brian/rets-client/node_modules/rets-client/dist/clientModules/metadata.js:24:12)
    at /home/brian/rets-client/node_modules/rets-client/dist/clientModules/metadata.js:171:18
From previous event:
    at module.exports._getParsedMetadataFactory (/home/brian/rets-client/node_modules/rets-client/dist/clientModules/metadata.js:161:30)
    at /home/brian/rets-client/retsexample.js:43:28
    at /home/brian/rets-client/node_modules/rets-client/dist/client.js:131:18
From previous event:
    at /home/brian/rets-client/node_modules/rets-client/dist/client.js:130:30
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at /home/brian/rets-client/node_modules/rets-client/dist/client.js:129:29
From previous event:
    at Object.Client.getAutoLogoutClient (/home/brian/rets-client/node_modules/rets-client/dist/client.js:126:26)
    at Object.<anonymous> (/home/brian/rets-client/retsexample.js:36:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.runMain [as _onTimeout] (module.js:467:10)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by zacronos** [comment] 2016-01-15 04:08
The error code 20513 indicates the server encountered an internal error, but without any other details of the nature of the error.  There's not much I can do without more information.  Please reach out to tech support with your RETS/MLS and see if they can tell you the cause of the error.  If the response they give you is informative enough, I will do my best to fix the problem.

I notice the RETS server you are querying is using RETS 1.5, so I wouldn't be surprised if that is part of the problem -- this library has only been tested with RETS 1.7.2 and RETS 1.8 servers.

**Comment by morr0350** [comment] 2016-01-19 17:45
I believe this is a case sensitivity issue: the ID query param should be all-caps, like:  http://rets.mresdms.com:8080/rets/rets/getMetadata?Type=METADATA-RESOURCE&ID=5280890&Format=COMPACT).   I tested this with "Id" and got the same <RETS ReplyCode="20513" ReplyText="Miscellaneous Error"/>, but with "ID" the request works.

**Comment by zacronos** [comment] 2016-01-19 18:25
Good catch, @morr0350!  v4.0.2 fixes ID param casing for metadata queries.  I'm going to close this ticket assuming this fixes it -- if it doesn't @briviere, please create a new ticket.

**Closed by zacronos** 2016-01-19 18:25 UTC

**Comment by briviere** [comment] 2016-01-20 14:03
It is working better but I'm getting an error on the OpenHouse Table Metadata request::

ERROR: issue encountered: TypeError: Cannot read property 'info' of undefined
    at /home/brian/rets-example/retsexample.js:74:37
From previous event:
    at /home/brian/rets-example/retsexample.js:70:10
    at /home/brian/rets-example/node_modules/rets-client/dist/client.js:131:18
From previous event:
    at /home/brian/rets-example/node_modules/rets-client/dist/client.js:130:30
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at /home/brian/rets-example/node_modules/rets-client/dist/client.js:129:29
From previous event:
    at Object.Client.getAutoLogoutClient (/home/brian/rets-example/node_modules/rets-client/dist/client.js:126:26)
    at Object.<anonymous> (/home/brian/rets-example/retsexample.js:36:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.runMain [as _onTimeout] (module.js:467:10)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by zacronos** [comment] 2016-01-20 14:30
@briviere  Just before the line causing the error (retsexample.js:74) which should look like `outputFields(data.results[0].info);`, can you put in `console.log('@@@@@@@'+JSON.stringify(data,null,2));` and send over the output from that?

**Comment by briviere** [comment] 2016-01-21 12:05
Here it is:

@@@@@@@{
  "results": [],
  "type": "METADATA-TABLE",
  "headerInfo": {
    "retsVersion": "RETS/1.5",
    "contentType": "text/xml",
    "contentLength": "87",
    "date": "Thu, 21 Jan 2016 12:04:14 GMT",
    "server": "Apache Coyote/1.0",
    "connection": "close"
  },
  "replyCode": "0",
  "replyTag": "OPERATION_SUCCESSFUL",
  "replyText": "Operation Successful",
  "entriesReceived": 0
}

Brian

**Comment by morr0350** [comment] 2016-01-21 13:53
What are you passing in your code as the Resource and Class in the call to client.metadata.getTable()? It looks like you're just getting an empty response and my first guess would be that either the Resource or Class name in the ID param aren't matching what the server expects.

**Comment by briviere** [comment] 2016-01-21 17:34
//get field data for open houses 
        return client.metadata.getTable("OpenHouse", "OPENHOUSE");

I'm just trying to run the rets session examples with updated ClientSettings and photoSourceId.  


Brian

**Comment by morr0350** [comment] 2016-01-21 17:49
The example session has example resources and classes in those parameters, but I would bet that the actual MRES/Black Knight server you are working with has a different name for the open house class.  Typically, MRES has the name "OPEN" rather than "OPENHOUSE" for the open house table.  Try `return client.metadata.getTable("OpenHouse", "OPEN");`  and see if that works.

**Comment by zacronos** [comment] 2016-01-21 17:54
As @morr0350 said, the example code in the README is just an example, and will likely need to be modified for your server's data schema.  The line `return client.metadata.getTable("OpenHouse", "OPENHOUSE");` blindly uses the IDs `"OpenHouse"` and `"OPENHOUSE"`, but your server may use different IDs, or for all I know (I haven't looked at the differences in RETS 1.5) it may not even have a separate Open House data table.

The output from `client.metadata.getResources()` will hopefully give you an idea of which ID you need to use in `client.metadata.getClass(*[something from the first query]*)`, and the output from that will give you an ID to use in `client.metadata.getTable(*[same thing from the first query]*, *[something from the second query]*);`.

**Comment by briviere** [comment] 2016-01-21 18:05
Yes that appears to be the case,  I will give the above a try.  Thanks for all your help, greatly appreciated :). 

Resource name: OpenHouse [OpenHouse]

Class name: OPEN []

Table name: PROPERTY_DISTRICT [] (1)

Table name: COUNTER [] (8)

Table name: OFFICE_NAME [] (1)

Table name: MLSNUM [ListingID] (1)

Table name: PROPERTY_SUB_DISTRICT [] (1)

Table name: NOTICE_COUNTER [ActivityID] (8)

Table name: ADDRESS [StreetAddress] (1)

Table name: OFFICE_ID [OfficeID] (8)

Table name: AGENT_ID [AgentID] (8)

Table name: OPEN_HOUSE_TYPE [] (1)

Table name: OPEN_HOUSE_REMARKS [ActivityComments] (1)

Table name: OPEN_HOUSE_AREA [] (1)

Table name: PROPERTY_DISTRICT_CODE [] (9)

Table name: OPEN_HOUSE_HOST_TYPE [] (1)

Table name: START_DATE_TIME [StartDateTime] (3)

Table name: PROPERTY_MAJOR_AREA_CODE [] (1)

Table name: PROPERTY_SUB_DISTRICT_CODE [] (1)

Table name: PROPERTY_PRICE [] (8)

Table name: PROPERTY_TYPE [] (1)

Table name: END_DATE_TIME [EndDateTime] (3)

Table name: PROPERTY_MAJOR_AREA [] (1)

Table name: BOARD_ID [Board] (1)

Table name: AGENT_NAME [] (1)
